import type { DistrictId, WeaponId } from '@/core/types';

/** All user-facing text (future localisation). */
export const STR = {
  title: 'BHEEM',
  subtitle: 'Liberate the Village',
  tagline: 'The Asura Horde has taken the hill village. Take it back.',
  menu: { play: 'PLAY', newGame: 'New Game', continue: 'CONTINUE', creative: 'CREATIVE MODE', settings: 'SETTINGS', pressStart: 'Press any key' },
  pause: { title: 'Paused', resume: 'Resume', restart: 'Restart', settings: 'Settings', quit: 'Main Menu' },
  rotate: 'Rotate your phone',
  arena: {
    names: { courtyard: 'Courtyard', training_yard: 'Training Yard', lava_forge: 'Lava Forge', sky_citadel: 'Sky Citadel' },
    windCatch: 'The wind catches you!',
  },
  creative: {
    title: 'Creative Mode',
    objectiveSandbox: 'Spawn foes from the Toolbox',
    objectiveBoss: 'Defeat the boss',
    badge: 'CREATIVE',
    sandbox: 'Sandbox - Training Yard',
    bossSelect: 'Boss Select',
    back: 'Back',
    fight: 'FIGHT!',
    boss: 'Boss',
    startPhase: 'Start phase',
    allies: 'Allies',
    alliesNone: 'None',
    alliesAuto: 'Auto-summon',
    skipIntro: 'Skip intro',
    on: 'ON',
    off: 'OFF',
    hp: 'HP',
    phases: 'Phases',
    bestTime: 'Best time',
    none: '--',
    miniBoss: 'ELITE BRUTE',
    miniBossTitle: 'Mini-Boss',
    estimate: (a: number, b: number) => `~${a}-${b} min`,
    bossDesc: {
      kaalasura: 'Four phases. Warbanners, Hollow Echoes, Dark Rain, Hellfire and a Last Stand.',
      brute: 'An elite Brute with armoured slams and charges. Uses the Story AI and stats.',
    },
    toolbox: 'Toolbox',
    god: 'God Mode',
    hazards: 'Hazards',
    paused: 'PAUSED',
    sandboxArena: 'Sandbox',
    arena: 'Arena',
    infPrana: 'Infinite Prana',
    infArrows: 'Infinite Arrows',
    instantRally: 'Instant Rally',
    noDashCd: 'No Dash Cooldown',
    slowMo: 'Slow Motion',
    dmgNumbers: 'Damage Numbers',
    spawn: 'Spawn',
    dummy: 'Spawn Training Dummy',
    pickup: 'Spawn Pickup',
    summon: 'Summon Squad',
    clear: 'Clear All',
    moves: 'Move List',
    close: 'Close',
    reset: 'Reset',
    resetHint: 'RESET [Bksp]',
    toolsHint: 'TOOLS [Tab]',
    bossesHint: 'BOSSES [B]',
    queued: (n: number) => `Enemy cap reached - ${n} queued`,
    died: 'You fell - RESET to restart the fight',
    resetDone: 'Reset',
    style: (n: number) => `${n} HIT STYLE`,
    result: 'Boss Defeated',
    time: 'Time',
    dmgTaken: 'Damage taken',
    hitsLanded: 'Hits landed',
    rematch: 'Rematch',
    newBest: 'NEW BEST TIME!',
    skip: 'Tap / Attack to skip',
    pickups: { health: 'Amrit Orb', prana: 'Prana Orb', arrows: 'Arrow Bundle' } as Record<string, string>,
    enemies: { raider: 'Raider', boneArcher: 'Bone Archer', mireHexer: 'Mire Hexer', skyCaller: 'Sky Caller', brute: 'Brute', imp: 'Imp' } as Record<string, string>,
    moveList: [
      'Move A/D or stick   Jump Space (hold = higher)',
      'Drop through: Down + Jump   Dash Shift (air dash)',
      'Sword: tap Attack x3 combo, timed hit deflects arrows',
      'Bow: hold Attack to charge, release to fire (pierces)',
      'Staff: tap = Bolt, hold = Thunderclap (costs Prana)',
      'Weapons 1/2/3 or Q   Summon squad R   Interact E',
    ],
  },
  settings: {
    title: 'Settings',
    master: 'Master Volume',
    music: 'Music Volume',
    sfx: 'SFX Volume',
    shake: 'Screen Shake',
    reduced: 'Reduced Effects',
    damageNumbers: 'Damage Numbers',
    fullscreen: 'Fullscreen',
    bindings: 'Key Bindings',
    back: 'Back',
    pressKey: 'Press a key... (Esc cancels)',
    reset: 'Reset Bindings',
    on: 'On',
    off: 'Off',
    touch: 'Touch Controls',
    touchAlways: 'Always show touch',
    touchSize: 'Button size',
    touchOpacity: 'Opacity',
    leftHanded: 'Left-handed',
    haptics: 'Haptics',
    quality: 'Graphics',
    qualityNames: { auto: 'Auto', high: 'High', low: 'Mobile' } as Record<string, string>,
    toolboxPauses: 'Toolbox pauses game',
    lowFpsToast: 'Low FPS: reduced effects on',
  },
  actions: {
    left: 'Move Left',
    right: 'Move Right',
    jump: 'Jump',
    crouch: 'Crouch / Drop',
    dash: 'Dash',
    attack: 'Attack',
    weapon1: 'Sword',
    weapon2: 'Bow',
    weapon3: 'Thunder Staff',
    cycleNext: 'Next Weapon',
    cyclePrev: 'Prev Weapon',
    summon: 'Summon Soldiers',
    interact: 'Interact',
    pause: 'Pause',
  },
  garjana: {
    name: 'GARJANA',
    title: 'the Storm Archer',
    desc: 'Sky Citadel. Wind Barrier, Storm Pylons and Judgment. Deflect his arrows!',
    phases: ['Gathering Clouds', 'Wind Barrier', 'Eye of the Storm', 'Tempest Ascendant'],
    barrier: 'BARRIER!',
    barrierTip: 'Arrows bounce off the Wind Barrier: use updrafts and the sword, or deflect his arrows',
    pylonTip: 'Destroy the 3 Storm Pylons to bring the storm down!',
    stormDown: 'STORM DOWN',
    judgment: "THUNDER GOD'S JUDGMENT",
    judgmentTip: 'Stand on a glowing pad!',
    perfect: 'PERFECT DEFLECT',
    hawksDown: 'Hawks down: barrier open!',
  },
  gameOver: {
    retryPhase: (n: number) => `Retry from phase ${n}`,
    phaseNote: 'Boss checkpoint: full health, Prana and arrows',
    title: 'The Horde takes the village',
    subtitle: 'Bheem has fallen',
    retry: 'Retry from shrine',
    menu: 'Main menu',
    coinLoss: (n: number) => `Lost ${n} coins`,
  },
  victory: {
    title: 'VILLAGE LIBERATED',
    subtitle: 'Kaalasura, the Hollow King, is no more',
    time: 'Time',
    deaths: 'Deaths',
    rescued: 'Villagers rescued',
    coins: 'Coins',
    kills: 'Asura slain',
    menu: 'Main menu',
    best: 'Best clear',
    score: 'Score',
    bestScore: 'Best score',
    newBest: 'NEW BEST!',
  },
  shrine: {
    title: 'Shrine of Light',
    subtitle: 'Offer coins for blessings',
    close: 'Leave (E / Esc)',
    maxed: 'MAX',
    notEnough: 'Not enough coins',
    purchased: 'Blessing received',
    activated: 'Shrine activated - checkpoint set',
  },
  upgrades: {
    might: { name: 'Might', desc: 'Sword and arrow damage +10%' },
    vitality: { name: 'Vitality', desc: 'Max HP +20' },
    quiver: { name: 'Quiver', desc: 'Max arrows +10' },
    prana: { name: 'Prana', desc: 'Max Prana +20, regen +1/s' },
    rally: { name: 'Rally', desc: 'Ally HP +25%, Rally per kill +1' },
  },
  weapons: { sword: 'Khadga', bow: 'Dhanush', staff: 'Vajra Danda' } as Record<WeaponId, string>,
  districts: {
    gate: 'Gate & Outskirts',
    market: 'Market Street',
    temple: 'Temple Hill',
    hall: "Chieftain's Hall",
  } as Record<DistrictId, string>,
  districtHints: {
    gate: 'Dash through attacks. Deflect arrows with the sword.',
    market: 'Kill the Mire Hexer to cleanse its Slow.',
    temple: 'Brutes glow gold when they cannot be staggered. Punish after the slam.',
    hall: 'Free the last captives before facing the warlord.',
  } as Record<DistrictId, string>,
  objectives: {
    enter: 'Push into the district',
    clear: (n: number) => `Defeat the garrison (${n} left)`,
    banner: 'Destroy the occupation banner',
    proceed: 'District liberated - move on',
    boss: 'Defeat Kaalasura',
    arena: 'Enter the courtyard',
  },
  prompts: {
    captive: 'Hold to free',
    shrine: 'Pray at shrine',
    shrineShop: 'Open shrine',
    chest: 'Open chest',
  },
  health: (pct: number): string => {
    if (pct >= 0.9) return 'You are in Perfect Health';
    if (pct >= 0.7) return 'You are Scratched';
    if (pct >= 0.45) return 'You are Wounded';
    if (pct >= 0.2) return 'You are Badly Wounded';
    return 'You are Barely Alive';
  },
  hud: {
    squadActive: 'Squad active',
    summonReady: 'SUMMON READY',
    rally: 'RALLY',
    slow: 'SLOWED',
    rescued: 'Rescued',
    coins: 'Coins',
    arrows: 'Arrows',
    multi: 'MULTI!',
    banner: 'BANNER',
    critical: 'CRITICAL HIT',
    pranaDry: 'No Prana',
    score: 'SCORE',
    garrisonCleared: 'GARRISON CLEARED',
    bannerFallen: 'BANNER FALLEN',
    districtLiberated: (name: string) => `DISTRICT LIBERATED - ${name.toUpperCase()}`,
    flawless: 'FLAWLESS',
    environment: 'ENVIRONMENT',
  },
  toasts: {
    captiveFreed: 'Villager freed! +15 Rally',
    squadUpgrade: 'Your squad grows stronger',
    liberated: (name: string) => `${name} liberated!`,
    gateOpen: 'The gate is open',
    slowCleansed: 'Slow cleansed!',
    deflect: 'Deflect!',
  },
  boss: {
    name: 'KAALASURA',
    title: 'The Hollow King',
    phase2: 'Call of the Horde',
    phase3: 'Hollow Fury',
    phases: ['The Warlord', 'Call of the Horde', 'Hollow Fury', 'Hollow King Ascendant'],
    break: 'BREAK!',
    breakTip: 'GUARD BROKEN! Hit hard while he is staggered',
    crate: 'Supply crate!',
    lastStand: 'LAST STAND',
    execute: 'EXECUTE!',
    wardTip: 'Kill the minions to break his ward!',
    hellfire: 'Hellfire! Stay inside the line',
    warbanner: 'Warbanner raised: destroy it!',
  },
  intro: { title: 'BHEEM', subtitle: 'The protector returns' },
  errors: {
    webgl: 'BHEEM needs WebGL. Please enable hardware acceleration or try another browser.',
    level: 'The level data could not be loaded.',
  },
  loading: 'Gathering the village...',
  skip: 'Hold any key to skip',
};
